import Head from "next/head";
import Image from "next/image";
import Bio from "../components/Bio";
import Contact from "../components/Contact";
import Navbar from "../components/Navbar";
import Projects from "../components/Projects";
import Skills from "../components/Skills";
import Footer from "../components/Footer";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ben Tijanic | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Skills />
      <Bio />
      <Projects />
      <Contact />
      <Footer />
    </div>
  );
}
